from pydantic import BaseModel, Field
from typing import Optional


class ClientData(BaseModel):
    """Données d'entrée pour la prédiction de scoring crédit — 175 features."""

    NAME_CONTRACT_TYPE: Optional[float] = Field(None, description="NAME_CONTRACT_TYPE")
    FLAG_OWN_CAR: Optional[float] = Field(None, description="FLAG_OWN_CAR")
    FLAG_OWN_REALTY: Optional[float] = Field(None, description="FLAG_OWN_REALTY")
    CNT_CHILDREN: Optional[float] = Field(None, description="CNT_CHILDREN")
    AMT_INCOME_TOTAL: Optional[float] = Field(None, description="AMT_INCOME_TOTAL")
    AMT_CREDIT: Optional[float] = Field(None, description="AMT_CREDIT")
    AMT_ANNUITY: Optional[float] = Field(None, description="AMT_ANNUITY")
    AMT_GOODS_PRICE: Optional[float] = Field(None, description="AMT_GOODS_PRICE")
    NAME_EDUCATION_TYPE: Optional[float] = Field(None, description="NAME_EDUCATION_TYPE")
    REGION_POPULATION_RELATIVE: Optional[float] = Field(None, description="REGION_POPULATION_RELATIVE")
    DAYS_BIRTH: Optional[float] = Field(None, description="DAYS_BIRTH")
    DAYS_EMPLOYED: Optional[float] = Field(None, description="DAYS_EMPLOYED")
    DAYS_REGISTRATION: Optional[float] = Field(None, description="DAYS_REGISTRATION")
    DAYS_ID_PUBLISH: Optional[float] = Field(None, description="DAYS_ID_PUBLISH")
    OWN_CAR_AGE: Optional[float] = Field(None, description="OWN_CAR_AGE")
    FLAG_MOBIL: Optional[float] = Field(None, description="FLAG_MOBIL")
    FLAG_EMP_PHONE: Optional[float] = Field(None, description="FLAG_EMP_PHONE")
    FLAG_WORK_PHONE: Optional[float] = Field(None, description="FLAG_WORK_PHONE")
    FLAG_CONT_MOBILE: Optional[float] = Field(None, description="FLAG_CONT_MOBILE")
    FLAG_PHONE: Optional[float] = Field(None, description="FLAG_PHONE")
    FLAG_EMAIL: Optional[float] = Field(None, description="FLAG_EMAIL")
    CNT_FAM_MEMBERS: Optional[float] = Field(None, description="CNT_FAM_MEMBERS")
    REGION_RATING_CLIENT: Optional[float] = Field(None, description="REGION_RATING_CLIENT")
    REGION_RATING_CLIENT_W_CITY: Optional[float] = Field(None, description="REGION_RATING_CLIENT_W_CITY")
    HOUR_APPR_PROCESS_START: Optional[float] = Field(None, description="HOUR_APPR_PROCESS_START")
    REG_REGION_NOT_LIVE_REGION: Optional[float] = Field(None, description="REG_REGION_NOT_LIVE_REGION")
    REG_REGION_NOT_WORK_REGION: Optional[float] = Field(None, description="REG_REGION_NOT_WORK_REGION")
    LIVE_REGION_NOT_WORK_REGION: Optional[float] = Field(None, description="LIVE_REGION_NOT_WORK_REGION")
    REG_CITY_NOT_LIVE_CITY: Optional[float] = Field(None, description="REG_CITY_NOT_LIVE_CITY")
    REG_CITY_NOT_WORK_CITY: Optional[float] = Field(None, description="REG_CITY_NOT_WORK_CITY")
    LIVE_CITY_NOT_WORK_CITY: Optional[float] = Field(None, description="LIVE_CITY_NOT_WORK_CITY")
    EXT_SOURCE_1: Optional[float] = Field(None, description="EXT_SOURCE_1")
    EXT_SOURCE_2: Optional[float] = Field(None, description="EXT_SOURCE_2")
    EXT_SOURCE_3: Optional[float] = Field(None, description="EXT_SOURCE_3")
    APARTMENTS_AVG: Optional[float] = Field(None, description="APARTMENTS_AVG")
    BASEMENTAREA_AVG: Optional[float] = Field(None, description="BASEMENTAREA_AVG")
    YEARS_BEGINEXPLUATATION_AVG: Optional[float] = Field(None, description="YEARS_BEGINEXPLUATATION_AVG")
    YEARS_BUILD_AVG: Optional[float] = Field(None, description="YEARS_BUILD_AVG")
    COMMONAREA_AVG: Optional[float] = Field(None, description="COMMONAREA_AVG")
    ELEVATORS_AVG: Optional[float] = Field(None, description="ELEVATORS_AVG")
    ENTRANCES_AVG: Optional[float] = Field(None, description="ENTRANCES_AVG")
    FLOORSMAX_AVG: Optional[float] = Field(None, description="FLOORSMAX_AVG")
    FLOORSMIN_AVG: Optional[float] = Field(None, description="FLOORSMIN_AVG")
    LANDAREA_AVG: Optional[float] = Field(None, description="LANDAREA_AVG")
    LIVINGAPARTMENTS_AVG: Optional[float] = Field(None, description="LIVINGAPARTMENTS_AVG")
    LIVINGAREA_AVG: Optional[float] = Field(None, description="LIVINGAREA_AVG")
    NONLIVINGAPARTMENTS_AVG: Optional[float] = Field(None, description="NONLIVINGAPARTMENTS_AVG")
    NONLIVINGAREA_AVG: Optional[float] = Field(None, description="NONLIVINGAREA_AVG")
    APARTMENTS_MODE: Optional[float] = Field(None, description="APARTMENTS_MODE")
    BASEMENTAREA_MODE: Optional[float] = Field(None, description="BASEMENTAREA_MODE")
    YEARS_BEGINEXPLUATATION_MODE: Optional[float] = Field(None, description="YEARS_BEGINEXPLUATATION_MODE")
    YEARS_BUILD_MODE: Optional[float] = Field(None, description="YEARS_BUILD_MODE")
    COMMONAREA_MODE: Optional[float] = Field(None, description="COMMONAREA_MODE")
    ELEVATORS_MODE: Optional[float] = Field(None, description="ELEVATORS_MODE")
    ENTRANCES_MODE: Optional[float] = Field(None, description="ENTRANCES_MODE")
    FLOORSMAX_MODE: Optional[float] = Field(None, description="FLOORSMAX_MODE")
    FLOORSMIN_MODE: Optional[float] = Field(None, description="FLOORSMIN_MODE")
    LANDAREA_MODE: Optional[float] = Field(None, description="LANDAREA_MODE")
    LIVINGAPARTMENTS_MODE: Optional[float] = Field(None, description="LIVINGAPARTMENTS_MODE")
    LIVINGAREA_MODE: Optional[float] = Field(None, description="LIVINGAREA_MODE")
    NONLIVINGAPARTMENTS_MODE: Optional[float] = Field(None, description="NONLIVINGAPARTMENTS_MODE")
    NONLIVINGAREA_MODE: Optional[float] = Field(None, description="NONLIVINGAREA_MODE")
    APARTMENTS_MEDI: Optional[float] = Field(None, description="APARTMENTS_MEDI")
    BASEMENTAREA_MEDI: Optional[float] = Field(None, description="BASEMENTAREA_MEDI")
    YEARS_BEGINEXPLUATATION_MEDI: Optional[float] = Field(None, description="YEARS_BEGINEXPLUATATION_MEDI")
    YEARS_BUILD_MEDI: Optional[float] = Field(None, description="YEARS_BUILD_MEDI")
    COMMONAREA_MEDI: Optional[float] = Field(None, description="COMMONAREA_MEDI")
    ELEVATORS_MEDI: Optional[float] = Field(None, description="ELEVATORS_MEDI")
    ENTRANCES_MEDI: Optional[float] = Field(None, description="ENTRANCES_MEDI")
    FLOORSMAX_MEDI: Optional[float] = Field(None, description="FLOORSMAX_MEDI")
    FLOORSMIN_MEDI: Optional[float] = Field(None, description="FLOORSMIN_MEDI")
    LANDAREA_MEDI: Optional[float] = Field(None, description="LANDAREA_MEDI")
    LIVINGAPARTMENTS_MEDI: Optional[float] = Field(None, description="LIVINGAPARTMENTS_MEDI")
    LIVINGAREA_MEDI: Optional[float] = Field(None, description="LIVINGAREA_MEDI")
    NONLIVINGAPARTMENTS_MEDI: Optional[float] = Field(None, description="NONLIVINGAPARTMENTS_MEDI")
    NONLIVINGAREA_MEDI: Optional[float] = Field(None, description="NONLIVINGAREA_MEDI")
    TOTALAREA_MODE: Optional[float] = Field(None, description="TOTALAREA_MODE")
    EMERGENCYSTATE_MODE: Optional[float] = Field(None, description="EMERGENCYSTATE_MODE")
    OBS_30_CNT_SOCIAL_CIRCLE: Optional[float] = Field(None, description="OBS_30_CNT_SOCIAL_CIRCLE")
    DEF_30_CNT_SOCIAL_CIRCLE: Optional[float] = Field(None, description="DEF_30_CNT_SOCIAL_CIRCLE")
    OBS_60_CNT_SOCIAL_CIRCLE: Optional[float] = Field(None, description="OBS_60_CNT_SOCIAL_CIRCLE")
    DEF_60_CNT_SOCIAL_CIRCLE: Optional[float] = Field(None, description="DEF_60_CNT_SOCIAL_CIRCLE")
    DAYS_LAST_PHONE_CHANGE: Optional[float] = Field(None, description="DAYS_LAST_PHONE_CHANGE")
    FLAG_DOCUMENT_2: Optional[float] = Field(None, description="FLAG_DOCUMENT_2")
    FLAG_DOCUMENT_3: Optional[float] = Field(None, description="FLAG_DOCUMENT_3")
    FLAG_DOCUMENT_4: Optional[float] = Field(None, description="FLAG_DOCUMENT_4")
    FLAG_DOCUMENT_5: Optional[float] = Field(None, description="FLAG_DOCUMENT_5")
    FLAG_DOCUMENT_6: Optional[float] = Field(None, description="FLAG_DOCUMENT_6")
    FLAG_DOCUMENT_7: Optional[float] = Field(None, description="FLAG_DOCUMENT_7")
    FLAG_DOCUMENT_8: Optional[float] = Field(None, description="FLAG_DOCUMENT_8")
    FLAG_DOCUMENT_9: Optional[float] = Field(None, description="FLAG_DOCUMENT_9")
    FLAG_DOCUMENT_10: Optional[float] = Field(None, description="FLAG_DOCUMENT_10")
    FLAG_DOCUMENT_11: Optional[float] = Field(None, description="FLAG_DOCUMENT_11")
    FLAG_DOCUMENT_12: Optional[float] = Field(None, description="FLAG_DOCUMENT_12")
    FLAG_DOCUMENT_13: Optional[float] = Field(None, description="FLAG_DOCUMENT_13")
    FLAG_DOCUMENT_14: Optional[float] = Field(None, description="FLAG_DOCUMENT_14")
    FLAG_DOCUMENT_15: Optional[float] = Field(None, description="FLAG_DOCUMENT_15")
    FLAG_DOCUMENT_16: Optional[float] = Field(None, description="FLAG_DOCUMENT_16")
    FLAG_DOCUMENT_17: Optional[float] = Field(None, description="FLAG_DOCUMENT_17")
    FLAG_DOCUMENT_18: Optional[float] = Field(None, description="FLAG_DOCUMENT_18")
    FLAG_DOCUMENT_19: Optional[float] = Field(None, description="FLAG_DOCUMENT_19")
    FLAG_DOCUMENT_20: Optional[float] = Field(None, description="FLAG_DOCUMENT_20")
    FLAG_DOCUMENT_21: Optional[float] = Field(None, description="FLAG_DOCUMENT_21")
    AMT_REQ_CREDIT_BUREAU_HOUR: Optional[float] = Field(None, description="AMT_REQ_CREDIT_BUREAU_HOUR")
    AMT_REQ_CREDIT_BUREAU_DAY: Optional[float] = Field(None, description="AMT_REQ_CREDIT_BUREAU_DAY")
    AMT_REQ_CREDIT_BUREAU_WEEK: Optional[float] = Field(None, description="AMT_REQ_CREDIT_BUREAU_WEEK")
    AMT_REQ_CREDIT_BUREAU_MON: Optional[float] = Field(None, description="AMT_REQ_CREDIT_BUREAU_MON")
    AMT_REQ_CREDIT_BUREAU_QRT: Optional[float] = Field(None, description="AMT_REQ_CREDIT_BUREAU_QRT")
    AMT_REQ_CREDIT_BUREAU_YEAR: Optional[float] = Field(None, description="AMT_REQ_CREDIT_BUREAU_YEAR")
    nb_credits_bureau: Optional[float] = Field(None, description="nb_credits_bureau")
    credit_actif: Optional[float] = Field(None, description="credit_actif")
    dette_totale: Optional[float] = Field(None, description="dette_totale")
    nb_demandes_prev: Optional[float] = Field(None, description="nb_demandes_prev")
    nb_approuves: Optional[float] = Field(None, description="nb_approuves")
    montant_moyen: Optional[float] = Field(None, description="montant_moyen")
    pos_nb_mois: Optional[float] = Field(None, description="pos_nb_mois")
    pos_mois_moyen: Optional[float] = Field(None, description="pos_mois_moyen")
    pos_sk_dpd_moyen: Optional[float] = Field(None, description="pos_sk_dpd_moyen")
    pos_sk_dpd_max: Optional[float] = Field(None, description="pos_sk_dpd_max")
    cc_nb_mois: Optional[float] = Field(None, description="cc_nb_mois")
    cc_balance_moyen: Optional[float] = Field(None, description="cc_balance_moyen")
    cc_balance_max: Optional[float] = Field(None, description="cc_balance_max")
    cc_dpd_moyen: Optional[float] = Field(None, description="cc_dpd_moyen")
    inst_nb_paiements: Optional[float] = Field(None, description="inst_nb_paiements")
    inst_montant_moyen: Optional[float] = Field(None, description="inst_montant_moyen")
    inst_retard_moyen: Optional[float] = Field(None, description="inst_retard_moyen")
    ratio_endettement: Optional[float] = Field(None, description="ratio_endettement")
    effort_remboursement: Optional[float] = Field(None, description="effort_remboursement")
    taux_approbation_hist: Optional[float] = Field(None, description="taux_approbation_hist")
    ratio_dette_revenu: Optional[float] = Field(None, description="ratio_dette_revenu")
    a_eu_retard: Optional[float] = Field(None, description="a_eu_retard")
    CODE_GENDER_M: Optional[float] = Field(None, description="CODE_GENDER_M")
    CODE_GENDER_XNA: Optional[float] = Field(None, description="CODE_GENDER_XNA")
    NAME_TYPE_SUITE_Family: Optional[float] = Field(None, description="NAME_TYPE_SUITE_Family")
    NAME_TYPE_SUITE_Group_of_people: Optional[float] = Field(None, description="NAME_TYPE_SUITE_Group of people")
    NAME_TYPE_SUITE_Other_A: Optional[float] = Field(None, description="NAME_TYPE_SUITE_Other_A")
    NAME_TYPE_SUITE_Other_B: Optional[float] = Field(None, description="NAME_TYPE_SUITE_Other_B")
    NAME_TYPE_SUITE_Spouse_partner: Optional[float] = Field(None, description="NAME_TYPE_SUITE_Spouse, partner")
    NAME_TYPE_SUITE_Unaccompanied: Optional[float] = Field(None, description="NAME_TYPE_SUITE_Unaccompanied")
    NAME_INCOME_TYPE_Commercial_associate: Optional[float] = Field(None, description="NAME_INCOME_TYPE_Commercial associate")
    NAME_INCOME_TYPE_Maternity_leave: Optional[float] = Field(None, description="NAME_INCOME_TYPE_Maternity leave")
    NAME_INCOME_TYPE_Pensioner: Optional[float] = Field(None, description="NAME_INCOME_TYPE_Pensioner")
    NAME_INCOME_TYPE_State_servant: Optional[float] = Field(None, description="NAME_INCOME_TYPE_State servant")
    NAME_INCOME_TYPE_Student: Optional[float] = Field(None, description="NAME_INCOME_TYPE_Student")
    NAME_INCOME_TYPE_Unemployed: Optional[float] = Field(None, description="NAME_INCOME_TYPE_Unemployed")
    NAME_INCOME_TYPE_Working: Optional[float] = Field(None, description="NAME_INCOME_TYPE_Working")
    NAME_FAMILY_STATUS_Married: Optional[float] = Field(None, description="NAME_FAMILY_STATUS_Married")
    NAME_FAMILY_STATUS_Separated: Optional[float] = Field(None, description="NAME_FAMILY_STATUS_Separated")
    NAME_FAMILY_STATUS_Single___not_married: Optional[float] = Field(None, description="NAME_FAMILY_STATUS_Single / not married")
    NAME_FAMILY_STATUS_Unknown: Optional[float] = Field(None, description="NAME_FAMILY_STATUS_Unknown")
    NAME_FAMILY_STATUS_Widow: Optional[float] = Field(None, description="NAME_FAMILY_STATUS_Widow")
    NAME_HOUSING_TYPE_House___apartment: Optional[float] = Field(None, description="NAME_HOUSING_TYPE_House / apartment")
    NAME_HOUSING_TYPE_Municipal_apartment: Optional[float] = Field(None, description="NAME_HOUSING_TYPE_Municipal apartment")
    NAME_HOUSING_TYPE_Office_apartment: Optional[float] = Field(None, description="NAME_HOUSING_TYPE_Office apartment")
    NAME_HOUSING_TYPE_Rented_apartment: Optional[float] = Field(None, description="NAME_HOUSING_TYPE_Rented apartment")
    NAME_HOUSING_TYPE_With_parents: Optional[float] = Field(None, description="NAME_HOUSING_TYPE_With parents")
    HOUSETYPE_MODE_specific_housing: Optional[float] = Field(None, description="HOUSETYPE_MODE_specific housing")
    HOUSETYPE_MODE_terraced_house: Optional[float] = Field(None, description="HOUSETYPE_MODE_terraced house")
    WALLSMATERIAL_MODE_Mixed: Optional[float] = Field(None, description="WALLSMATERIAL_MODE_Mixed")
    WALLSMATERIAL_MODE_Monolithic: Optional[float] = Field(None, description="WALLSMATERIAL_MODE_Monolithic")
    WALLSMATERIAL_MODE_Others: Optional[float] = Field(None, description="WALLSMATERIAL_MODE_Others")
    WALLSMATERIAL_MODE_Panel: Optional[float] = Field(None, description="WALLSMATERIAL_MODE_Panel")
    WALLSMATERIAL_MODE_Stone_brick: Optional[float] = Field(None, description="WALLSMATERIAL_MODE_Stone, brick")
    WALLSMATERIAL_MODE_Wooden: Optional[float] = Field(None, description="WALLSMATERIAL_MODE_Wooden")
    FONDKAPREMONT_MODE_org_spec_account: Optional[float] = Field(None, description="FONDKAPREMONT_MODE_org spec account")
    FONDKAPREMONT_MODE_reg_oper_account: Optional[float] = Field(None, description="FONDKAPREMONT_MODE_reg oper account")
    FONDKAPREMONT_MODE_reg_oper_spec_account: Optional[float] = Field(None, description="FONDKAPREMONT_MODE_reg oper spec account")
    WEEKDAY_APPR_PROCESS_START_MONDAY: Optional[float] = Field(None, description="WEEKDAY_APPR_PROCESS_START_MONDAY")
    WEEKDAY_APPR_PROCESS_START_SATURDAY: Optional[float] = Field(None, description="WEEKDAY_APPR_PROCESS_START_SATURDAY")
    WEEKDAY_APPR_PROCESS_START_SUNDAY: Optional[float] = Field(None, description="WEEKDAY_APPR_PROCESS_START_SUNDAY")
    WEEKDAY_APPR_PROCESS_START_THURSDAY: Optional[float] = Field(None, description="WEEKDAY_APPR_PROCESS_START_THURSDAY")
    WEEKDAY_APPR_PROCESS_START_TUESDAY: Optional[float] = Field(None, description="WEEKDAY_APPR_PROCESS_START_TUESDAY")
    WEEKDAY_APPR_PROCESS_START_WEDNESDAY: Optional[float] = Field(None, description="WEEKDAY_APPR_PROCESS_START_WEDNESDAY")
    OCCUPATION_RISK: Optional[float] = Field(None, description="OCCUPATION_RISK")
    ORGANIZATION_RISK: Optional[float] = Field(None, description="ORGANIZATION_RISK")


class PredictionResponse(BaseModel):
    """Réponse de l'API avec le score et la décision."""

    client_id: Optional[str] = Field(None, description="Identifiant client")
    score: float = Field(..., description="Probabilité de défaut (0-1)")
    decision: str = Field(..., description="ACCORD ou REFUS")
    seuil: float = Field(..., description="Seuil de décision utilisé")
    latence_ms: float = Field(..., description="Temps d'inférence en millisecondes")